[package]
name = "reading-queue-testbed-server"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "generate-openapi"
path = "src/bin/generate-openapi.rs"

[[bin]]
name = "migrate"
path = "src/bin/migrate.rs"

[dependencies]
axum.workspace = true
product-application = { package = "reading-queue-testbed-application", path = "../application" }
product-persistence-postgres = { package = "reading-queue-testbed-persistence-postgres", path = "../persistence-postgres" }
product-transport-http = { package = "reading-queue-testbed-transport-http", path = "../transport-http" }
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
