// SPDX-License-Identifier: MIT OR Apache-2.0

import path from "node:path";

import { defineConfig } from "orval";

function requiredAbsolutePath(name) {
  const value = process.env[name];
  if (!value || !path.isAbsolute(value)) {
    throw new Error(`${name} must be an absolute path supplied by yydra`);
  }
  return value;
}

const input = requiredAbsolutePath("YYDRA_OPENAPI_INPUT");
const output = requiredAbsolutePath("YYDRA_GENERATED_API_OUTPUT");

export default defineConfig({
  publicApi: {
    input: { target: input },
    output: {
      target: path.join(output, "fetch", "client.ts"),
      schemas: {
        path: path.join(output, "fetch", "schemas"),
        type: "zod",
      },
      client: "fetch",
      clean: true,
      formatter: "prettier",
      override: {
        header: () => [
          "SPDX-License-Identifier: MIT OR Apache-2.0",
          "Generated by Orval.",
          "Do not edit manually.",
        ],
        fetch: {
          runtimeValidation: true,
          useRuntimeFetcher: true,
        },
        zod: {
          version: 4,
          strict: {
            body: false,
            header: false,
            param: false,
            query: false,
            response: false,
          },
        },
      },
    },
  },
  requestSchemas: {
    input: { target: input },
    output: {
      target: path.join(output, "request", "contracts.ts"),
      schemas: {
        path: path.join(output, "request", "schemas"),
        type: "zod",
      },
      client: "zod",
      clean: true,
      formatter: "prettier",
      override: {
        header: () => [
          "SPDX-License-Identifier: MIT OR Apache-2.0",
          "Generated by Orval.",
          "Do not edit manually.",
        ],
        zod: {
          version: 4,
          strict: {
            body: true,
            header: true,
            param: true,
            query: true,
            response: true,
          },
          generateReusableSchemas: true,
        },
      },
    },
  },
});
